version: '3'

services:
  entity-linking-service:
    build: .
    restart: always
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn run:app --host 0.0.0.0 --port 8000
